name: Android
on:
  # push:
  #   paths-ignore:
  #     - 'doc/**'
  #     - '**.md'
  #     - '**.rdoc'
  # pull_request:
  #   paths-ignore:
  #     - 'doc/**'
  #     - '**.md'
  #     - '**.rdoc'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

jobs:
  make:
    strategy:
      matrix:
        include:
          - abi: armv7a-linux-androideabi
            name: armeabi-v7a
            api_level: 26
          - abi: aarch64-linux-android
            name: arm64-v8a
            api_level: 26
          - abi: i686-linux-android
            name: x86
            api_level: 26
          - abi: x86_64-linux-android
            name: x86_64
            api_level: 26
      fail-fast: false
    env:
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    if: ${{ !startsWith(github.event.head_commit.message, '[DOC]') && !contains(github.event.pull_request.labels.*.name, 'Documentation') }}
    steps:
      - run: mkdir build install
        working-directory:
      - name: Set ENV
        run: |
          echo "MAKEFLAGS=-j$((1 + $(nproc --all)))" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=${ANDROID_NDK_LATEST_HOME}" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=${ANDROID_NDK_LATEST_HOME}" >> $GITHUB_ENV
          echo "ANDROID_NDK=${ANDROID_NDK_LATEST_HOME}" >> $GITHUB_ENV
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y \
            build-essential \
            libssl-dev libyaml-dev \
            zlib1g-dev libncurses5-dev libffi-dev \
            bison autoconf ruby ccache
      - name: git config
        run: |
          git config --global advice.detachedHead 0
          git config --global init.defaultBranch garbage
      - uses: actions/checkout@v5
        with:
          path: src
      - uses: actions/cache@v5
        with:
          path: src/.downloaded-cache
          key: downloaded-cache
      - uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-android-${{ matrix.abi }}
      - run: export libdir="${{ github.workspace }}/installed/lib"
      - name: Change permissions
        run: |
          sudo chmod -R 777 /var/lib
      - name: Set up Android NDK
        run: |
          echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
      - name: Verify NDK Toolchain
        run: |
          clang --version
      - run: ./autogen.sh
        working-directory: src
        env:
          LIBDIR: "${{ github.workspace }}/installed/lib"
      - name: Run configure
        env:
          CFLAGS: "-std=gnu99 -O3 -flto=auto"
          LDFLAGS: "-flto=auto -fuse-ld=lld"
          AR: "llvm-ar"
          NM: "llvm-nm"
          RANLIB: "llvm-ranlib"
          CC: "ccache ${{ matrix.abi }}${{ matrix.api_level }}-clang"
          CXX: "ccache ${{ matrix.abi }}${{ matrix.api_level }}-clang++"
        run: >-
          ../src/configure -C --disable-install-doc
          --disable-install-bin
          --enable-shared
          --prefix="${{ github.workspace }}/installed"
          --host=${{ matrix.abi }}${{ matrix.api_level }}
          --enable-install-static-library
          --with-out-ext=openssl,readline,dbm,gdbm,win32ole
          --with-static-linked-ext
          --disable-rubygems
          --without-gmp
      - run: make
      - name: make install
        run: |
          make install-nodoc
      - name: Delete useless ruby executable
        run: rm -f ${{ github.workspace }}/installed/bin/ruby
      - name: Create bash mock wrapper for FindRuby.cmake
        uses: step-security/create-a-file-action@v0
        with:
          path: ${{ github.workspace }}/installed/bin
          isAbsolutePath: true
          file: 'ruby'
          content: |
            RUBY_PATH=$(readlink -f "$0/..")
            if [[ "$*" == *"'MAJOR'"* ]]; then
                echo -n "3"
            if [[ "$*" == *"'MINOR'"* ]]; then
                echo -n "1"
            if [[ "$*" == *"'TEENY'"* ]]; then
                echo -n "3"
            elif [[ "$*" == *"'arch'"* ]]; then
                echo -n "aarch64-linux-android26-android"
            elif [[ "$*" == *"'archdir'"* ]]; then
                echo -n "${RUBY_PATH}/lib/ruby/3.1.0/aarch64-linux-android26-android"
            elif [[ "$*" == *"'DLEXT'"* ]]; then
                echo -n "so"
            elif [[ "$*" == *"'rubyhdrdir'"* ]]; then
                echo -n "${RUBY_PATH}/include/ruby-3.1.0"
            elif [[ "$*" == *"'rubyarchhdrdir'"* ]]; then
                echo -n "${RUBY_PATH}/include/ruby-3.1.0/aarch64-linux-android26-android"
            elif [[ "$*" == *"'libdir'"* ]]; then
                echo -n "${RUBY_PATH}/lib"
            elif [[ "$*" == *"'RUBY_SO_NAME'"* ]]; then
                echo -n "ruby"
            elif [[ "$*" == *"'vendorarchdir'"* ]]; then
                echo -n "false"
            fi
      - name: Make bash mock wrapper executable
        run: chmod +x ${{ github.workspace }}/installed/bin/ruby
      - name: Create .bat mock wrapper for FindRuby.cmake
        uses: step-security/create-a-file-action@v0
        with:
          path: ${{ github.workspace }}/installed/bin
          isAbsolutePath: true
          file: 'ruby.bat'
          content: |
            @echo off
            setlocal enabledelayedexpansion

            for %%I in ("%~dp0..") do set "RUBY_PATH_RAW=%%~fI"
            set "RUBY_PATH=!RUBY_PATH_RAW:\=/!"

            set "ARGS=%*"

            if not "!ARGS:'MAJOR'=!" == "!ARGS!" (
                <nul set /p ="3"
            ) else if not "!ARGS:'MINOR'=!" == "!ARGS!" (
                <nul set /p ="1"
            ) else if not "!ARGS:'TEENY'=!" == "!ARGS!" (
                <nul set /p ="3"
            ) else if not "!ARGS:'arch'=!" == "!ARGS!" (
                <nul set /p ="x86_64-linux-android26-android"
            ) else if not "!ARGS:'archdir'=!" == "!ARGS!" (
                <nul set /p ="!RUBY_PATH!/lib/ruby/3.1.0/x86_64-linux-android26-android"
            ) else if not "!ARGS:'DLEXT'=!" == "!ARGS!" (
                <nul set /p ="so"
            ) else if not "!ARGS:'rubyhdrdir'=!" == "!ARGS!" (
                <nul set /p ="!RUBY_PATH!/include/ruby-3.1.0"
            ) else if not "!ARGS:'rubyarchhdrdir'=!" == "!ARGS!" (
                <nul set /p ="!RUBY_PATH!/include/ruby-3.1.0/x86_64-linux-android26-android"
            ) else if not "!ARGS:'libdir'=!" == "!ARGS!" (
                <nul set /p ="!RUBY_PATH!/lib"
            ) else if not "!ARGS:'RUBY_SO_NAME'=!" == "!ARGS!" (
                <nul set /p ="ruby"
            ) else if not "!ARGS:'vendorarchdir'=!" == "!ARGS!" (
                <nul set /p ="false"
            )
            endlocal
      - name: Create artifacts
        run: |
          mkdir -p ${{ github.workspace }}/installed/lib/ruby/gems/3.1.0/
          cp -r /var/lib/gems/3.1.0/ ${{ github.workspace }}/installed/lib/ruby/gems/3.1.0/
      - uses: actions/upload-artifact@v7
        with:
          name: ruby-android-${{ matrix.abi }}
          path: ${{ github.workspace }}/installed

defaults:
  run:
    working-directory: build
