name: Android
on:
  # push:
  #   paths-ignore:
  #     - 'doc/**'
  #     - '**.md'
  #     - '**.rdoc'
  # pull_request:
  #   paths-ignore:
  #     - 'doc/**'
  #     - '**.md'
  #     - '**.rdoc'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

jobs:
  make:
    strategy:
      matrix:
        include:
          - abi: armv7a-linux-androideabi
            name: armeabi-v7a
            api_level: 26
          - abi: aarch64-linux-android
            name: arm64-v8a
            api_level: 26
          - abi: i686-linux-android
            name: x86
            api_level: 26
          - abi: x86_64-linux-android
            name: x86_64
            api_level: 26
      fail-fast: false
    env:
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    if: ${{ !startsWith(github.event.head_commit.message, '[DOC]') && !contains(github.event.pull_request.labels.*.name, 'Documentation') }}
    steps:
      - run: mkdir build install
        working-directory:
      - name: Set ENV
        run: |
          echo "GNUMAKEFLAGS=-j$((1 + $(nproc --all)))" >> $GITHUB_ENV
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y \
            build-essential \
            libssl-dev libyaml-dev \
            zlib1g-dev libncurses5-dev libffi-dev \
            bison autoconf ruby
      - name: git config
        run: |
          git config --global advice.detachedHead 0
          git config --global init.defaultBranch garbage
      - uses: actions/checkout@v4
        with:
          path: src
      - uses: actions/cache@v4
        with:
          path: src/.downloaded-cache
          key: downloaded-cache
      - run: export libdir="${HOME}/ruby/lib"
      - name: Change permissions
        run: |
          sudo chmod -R 777 /var/lib
      - name: Set up Android NDK
        run: |
          echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
      - name: Verify NDK Toolchain
        run: |
          clang --version
      - run: ./autogen.sh
        working-directory: src
        env:
          LIBDIR: "${HOME}/ruby/lib"
      - name: Run configure
        env:
          CFLAGS: "-std=gnu99 -O3 -flto"
          LDFLAGS: "-flto"
        run: >-
          ../src/configure -C --disable-install-doc
          --disable-install-bin
          --prefix="${HOME}/ruby"
          --host=${{ matrix.abi }}${{ matrix.api_level }}
          --enable-install-static-library
          --with-out-ext=openssl,readline,dbm,gdbm,win32ole
          --with-static-linked-ext
          --disable-rubygems
          --without-gmp
      - run: make
      - name: make install
        run: |
          make install-nodoc

defaults:
  run:
    working-directory: build
