name: macOS
on:
  # push:
  #   paths-ignore:
  #     - 'doc/**'
  #     - '**.md'
  #     - '**.rdoc'
  # pull_request:
  #   paths-ignore:
  #     - 'doc/**'
  #     - '**.md'
  #     - '**.rdoc'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

jobs:
  make:
    env:
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[DOC]') && !contains(github.event.pull_request.labels.*.name, 'Documentation') }}
    steps:
      - run: mkdir build
        working-directory:
      - name: git config
        run: |
          git config --global advice.detachedHead 0
          git config --global init.defaultBranch garbage
      - uses: actions/checkout@v4
        with:
          path: src
      - uses: actions/cache@v4
        with:
          path: src/.downloaded-cache
          key: downloaded-cache
      - name: Install libraries
        run: |
          brew upgrade
          brew install libffi zlib autoconf automake libtool
        working-directory: src
      - name: Set ENV
        run: |
          echo "MAKEFLAGS=-j$((1 + $(sysctl -n hw.activecpu)))" >> $GITHUB_ENV
      - run: ./autogen.sh
        working-directory: src
      - name: Run configure
        run: ../src/configure -C --disable-install-doc --disable-install-bin --enable-install-static-library --with-out-ext=openssl,readline,dbm,gdbm,win32ole --with-static-linked-ext --disable-rubygems --without-gmp
        env:
          CFLAGS: "-std=gnu99 -flto"
          LDFLAGS: "-flto"
      - run: make
      - name: make install
        run: |
          make install-nodoc

defaults:
  run:
    working-directory: build
