name: Windows
on:
  # push:
  #   paths-ignore:
  #     - 'doc/**'
  #     - '**.md'
  #     - '**.rdoc'
  # pull_request:
  #   paths-ignore:
  #     - 'doc/**'
  #     - '**.md'
  #     - '**.rdoc'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

jobs:
  make:
    strategy:
      matrix:
        include:
          - vs: 2022
            os: windows-2022
            vcvars: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
          # - vs: 2026
          #   os: windows-2025-vs2026
          #   vcvars: '"C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.event.head_commit.message, '[DOC]') && !contains(github.event.pull_request.labels.*.name, 'Documentation') }}
    name: Visual Studio ${{ matrix.vs }}
    env:
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
      VCVARS: ${{ matrix.vcvars }}
    steps:
      - run: md build
        working-directory:
      - uses: actions/cache@v4
        with:
          path: C:\vcpkg\downloads
          key: ${{ runner.os }}-vcpkg-download-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-download-${{ matrix.os }}-
            ${{ runner.os }}-vcpkg-download-
      - name: Install libraries with vcpkg
        run: |
          vcpkg --triplet x64-windows install zlib
      - uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-chocolatey-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-chocolatey-${{ matrix.os }}-
            ${{ runner.os }}-chocolatey-
      - name: Install libraries with chocolatey
        uses: crazy-max/ghaction-chocolatey@v4
        with:
          args: install winflexbison3
      - name: git config
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global advice.detachedHead 0
          git config --global init.defaultBranch garbage
      - uses: actions/checkout@v4
        with:
          path: src
      - uses: actions/cache@v4
        with:
          path: src/.downloaded-cache
          key: downloaded-cache
      - name: Configure
        run: |
          call %VCVARS% 10.0.22621.0
          ../src/win32/configure.bat --disable-install-doc --disable-install-bin --enable-install-static-library --with-out-ext=openssl,readline,dbm,gdbm,win32ole --with-static-linked-ext --disable-rubygems --without-gmp --enable-bundled-libffi --with-opt-dir=C:/vcpkg/installed/x64-windows
      - name: Build
        run: |
          call %VCVARS% 10.0.22621.0
          nmake
        env:
          YACC: win_bison
      - name: Copy necessary DLLs
        run: |
          for %I in (C:\vcpkg\installed\x64-windows\bin\*.dll) do @(
            if not "%~nI" == "readline" copy /Y "%I" "%~nxI"
          )
      - name: Install
        run: |
          call %VCVARS% 10.0.22621.0
          nmake install
defaults:
  run:
    working-directory: build
    shell: cmd
